#!/bin/bash
#ddev-generated

## Description: Run unlighthouse-ci and prepare reports
## Usage: unlighthouse-ci
## Example: "ddev unlighthouse-ci"
## ExecRaw: true
# export NODE_TLS_REJECT_UNAUTHORIZED='0'

FOLDER=${1:-'local'}
FILE=${2:-'unlighthouse.ts'}

unlighthouse-ci --build-static --config-file=./config/$FOLDER/$FILE --output-path=./export/$FILE ${@:3}